name: mlsp
channels:
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - anyio=3.5.0
  - aom=3.6.0
  - appnope=0.1.2
  - archspec=0.2.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - black=23.11.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cctools=949.0.1
  - cctools_osx-64=949.0.1
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfgv=3.4.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - comm=0.1.2
  - conda=23.10.0
  - conda-build=3.28.2
  - conda-index=0.3.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - cytoolz=0.12.2
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.6
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - flake8=6.1.0
  - fmt=9.1.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - hdf5=1.12.1
  - icu=73.1
  - identify=2.5.5
  - idna=3.4
  - imagecodecs=2023.1.23
  - importlib-metadata=6.0.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - isort=5.9.3
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.12
  - ld64=530
  - ld64_osx-64=530
  - ldid=2.1.5
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.6.2
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - menuinst=2.0.1
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - nodeenv=1.7.0
  - notebook-shim=0.2.3
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - patch=2.7.6
  - pathspec=0.10.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - pre-commit=3.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pybind11-abi=4
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pyflakes=3.1.0
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-libarchive-c=2.9
  - pytorch=2.1.1
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.21
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tapi=1000.10.8
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - truststore=0.8.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - ukkonen=1.0.1
  - urllib3=1.26.18
  - virtualenv=20.17.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - deepinv==0.1.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - fastmri==0.3.0
      - fonttools==4.46.0
      - frozenlist==1.4.0
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h5py==3.10.0
      - hdf5storage==0.1.19
      - imageio==2.33.1
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.0
      - matplotlib==3.8.2
      - multidict==6.0.4
      - packaging==23.2
      - pandas==2.1.4
      - protobuf==4.25.1
      - psutil==5.9.6
      - pyparsing==3.1.1
      - pytorch-lightning==2.1.2
      - runstats==2.0.0
      - scikit-image==0.22.0
      - sentry-sdk==1.39.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tifffile==2023.12.9
      - torchmetrics==1.2.1
      - tqdm==4.66.1
      - tzdata==2023.3
      - wandb==0.16.1
      - yarl==1.9.4
